### ISSUE TITLE
deprecated - Retrieve a list of issues that have the value of this sprint

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/experimentsWithGithub#11]
The logical progression seems to be to dig deeper and deeper starting at the organization.

**Comment by mikeaintworkin** [comment]
- [ ] Access the dataverse organization

**Comment by mreekie** [comment]
Get the project number that I want.
- use a query that starts at the org and find the project by name

{ organization(login: "IQSS") 
  { projectsV2(first: 20, orderBy: {field: NUMBER, direction: ASC}, query: "Dataverse_Global_Backlog") 
    { nodes
      { id
        number
        title
        closed
      }
    }
    id
    email
    projectsUrl
  }
}

xxx - {'data': {'organization': {'projectsV2': {'nodes': [{'id': 'PVT_kwDOAApNpc4AHKIs', 'number': 34, 'title': 'Dataverse_Global_Backlog', 'closed': False}]}, 'id': 'MDEyOk9yZ2FuaXphdGlvbjY3NTIzNw==', 'email': None, 'projectsUrl': 'https://github.com/orgs/IQSS/projects'}}}

---
34

**Comment by mreekie** [comment]
query = """
{ organization(login: "IQSS") 
  { projectV2(number: 34)
    { title
      
    }
    id
    email
    projectsUrl
    login 
  }
}
---
xxx - {'data': {'organization': {'projectV2': {'title': 'Dataverse_Global_Backlog'}, 'id': 'MDEyOk9yZ2FuaXphdGlvbjY3NTIzNw==', 'email': None, 'projectsUrl': 'https://github.com/orgs/IQSS/projects', 'login': 'IQSS'}}}

**Comment by mikeaintworkin** [comment]
deprecating this issue and renaming issue #10 
This will reflect the change in the path of the investigation
