### ISSUE TITLE
Create a tabular output of all the issues and & PRs in the global backlog

### ISSUE THREAD

**Issue by mreekie** [thisaintwork/experimentsWithGithub#14]
This is based on work done in: [Retrieve *all* of the issues & PRs in the global backlog](https://github.com/thisaintwork/experimentsWithGithub/issues/12)

In this step I will create clean, complete tabular data from a dump of all the issues and PRS that are present in the backlog

This work will include:
- parsing out the size associated with each PR/Issue cleanly.
- Including a header line.

**Comment by mikeaintworkin** [comment]
Checked in. This one was relatively easy.
There is one portion of the xslt where I think I should be recursing but that's hard so I took the easy way out.
